### ISSUE TITLE
Problem 6 Solution

### ISSUE THREAD

**Issue by yuvrajverma01** [ankay212000/New_Learners_C-plus_plus_programming#14]
Really pushing up issues. Although I know it's _first come first serve basis_, but can I get a chance to this.
I am very much _new_ to Git and GitHub, trying hard to get assigned.
**Can I try** Ankay? :)

**Comment by GTron-1729** [comment]
hey @ankay212000. I would love to do this 👍

**Comment by ankay212000** [comment]
> Really pushing up issues. Although I know it's _first come first serve basis_, but can I get a chance to this.
> I am very much _new_ to Git and GitHub, trying hard to get assigned.
> **Can I try** Ankay? :)

Do see what the problem demands and how the solution has to be submitted ( refer readme file )

**Comment by ankay212000** [comment]
It's @GTron-1729 , @yuvrajverma01  it's already assigned
Due to first come first serve.....

**Comment by bhaveshgoyal182** [comment]
Thanks @ankay212000 for assigning.🙏

Please check the same with the PR posted.
If any changes required do let me know.
Thanks Again.🙏

**Comment by GTron-1729** [comment]
So can I work on it or is it assigned to yuvraj only? @ankay212000

**Comment by yuvrajverma01** [comment]
@GTron-1729 It's assigned to someone else.
No worries @ankay212000 , appreciated your efforts.✌

**Comment by GTron-1729** [comment]
@yuvrajverma01  well you can check my repositories and I will check urs and will suggest some changes. cheers 🍻!
